"""412555fe solver — Dihedral symmetry completion.

Rule: The output is the input made symmetric under the group generated by
transpose T: (r,c)->(c,r) and row-mirror M: (r,c)->(H+1-r,c).
Each cell belongs to an orbit of up to 8 positions.  Exactly one color (the
"filler") occupies the asymmetric positions; it is replaced by the value found
at the corresponding orbit partner.

Filler detection: count which input color most often sits on the minority side
of transpose violations (orbit positions disagree → the rare value is filler).
"""

from collections import Counter
from typing import List

Grid = List[List[int]]


def _orbit(r: int, c: int, H: int) -> list[tuple[int, int]]:
    s = H + 1
    pts = {
        (r, c), (c, r),
        (s - r, c), (c, s - r),
        (r, s - c), (s - c, r),
        (s - r, s - c), (s - c, s - r),
    }
    return [(rr, cc) for rr, cc in pts if 0 <= rr < H and 0 <= cc < H]


def _detect_filler(grid: Grid, H: int) -> int | None:
    votes: Counter = Counter()
    for r in range(H):
        for c in range(r + 1, H):
            if grid[r][c] != grid[c][r]:
                orb = _orbit(r, c, H)
                vals = Counter(grid[rr][cc] for rr, cc in orb)
                half = len(orb) // 2
                for v, cnt in vals.items():
                    if cnt < half:
                        votes[v] += 1
    return votes.most_common(1)[0][0] if votes else None


def transform(grid: Grid) -> Grid:
    H = len(grid)
    filler = _detect_filler(grid, H)
    if filler is None:
        return [row[:] for row in grid]

    out = [row[:] for row in grid]
    for r in range(H):
        for c in range(H):
            if grid[r][c] == filler:
                for rr, cc in _orbit(r, c, H):
                    if grid[rr][cc] != filler:
                        out[r][c] = grid[rr][cc]
                        break
    return out


solve = transform
