from __future__ import annotations
"""
auto_primitive_injector.py
--------------------------
Given a verified LLM-generated solve() function, injects it into the DSL
so the solver can use it immediately (both on disk and in the live module cache).

For rule-based ProgramCandidates the DSL already knows the op, so no injection
is needed – the solver will re-run and find the program.
"""
import re
import importlib
import sys
import textwrap
from pathlib import Path
from typing import Callable, Optional

_DSL_ROOT = Path(__file__).parents[2] / "dsl"
_TRANSFORMS_PATH = _DSL_ROOT / "advanced_transforms.py"
_PRIMITIVES_PATH = _DSL_ROOT / "primitives.py"
_TYPE_CHECKER_PATH = _DSL_ROOT / "type_checker.py"
_TRANSFORMS_DISPATCH_PATH = _DSL_ROOT / "transforms.py"
_GRAMMAR_PATH = Path(__file__).parents[2] / "synthesis" / "grammar.py"


def _op_name(task_id: str) -> str:
    """Derive a deterministic op name from the task ID."""
    safe = task_id.replace("-", "_").upper()
    return f"LLM_{safe}"


def inject_llm_solve(task_id: str, solve_fn: Callable) -> str:
    """
    Inject a verified LLM solve() function into the DSL.

    Steps:
    1. Append the function to advanced_transforms.py under a new name
    2. Register it in primitives.py GRID_OPS with arity 0
    3. Add it to VALID_OPS in type_checker.py
    4. Add a dispatch line in transforms.py
    5. Add it to SOLVER_FAMILIES and grammar.py program generation
    6. Reload the affected modules in-process

    Returns the op name used.
    """
    op = _op_name(task_id)
    fn_name = op.lower()
    code: str = getattr(solve_fn, "_llm_code", None) or ""

    if not code:
        print(f"[Injector] No code attached to solve_fn for {task_id}.")
        return op

    # --- 1. Append to advanced_transforms.py ---
    wrapper = textwrap.dedent(f"""

    # LLM-generated primitive for task {task_id}
    def {fn_name}(grid, background=0):
        \"\"\"Auto-generated by Gemini Flash for task {task_id}.\"\"\"
        import numpy as _np
        g = as_grid(grid).copy()
        # --- Begin LLM code ---
    """)
    # Indent the solve body by 4 spaces
    llm_body = "\n".join("    " + line for line in code.splitlines())
    wrapper += llm_body + "\n    # --- End LLM code ---\n"

    # Replace the solve() call with the wrapper shape
    # Actually simpler: just embed the raw solve fn under fn_name
    full_fn = textwrap.dedent(f"""

    # LLM-generated primitive for task {task_id}
    def {fn_name}(grid, background=0):
        \"\"\"Auto-generated by Gemini Flash for task {task_id}.\"\"\"
        import numpy as np
        g = as_grid(grid).copy()

    """)
    # Re-use the raw code by defining a nested solve inside
    indented_code = textwrap.indent(code, "    ") + "\n    return solve(g)\n"
    full_fn += indented_code

    with open(_TRANSFORMS_PATH, "a", encoding="utf-8") as f:
        f.write(full_fn)
    print(f"[Injector] Appended {fn_name}() to {_TRANSFORMS_PATH.name}")

    # --- 2. Register in primitives.py ---
    _append_to_grid_ops(op, arity=0)

    # --- 3. Add to VALID_OPS in type_checker.py ---
    _add_to_valid_ops(op)

    # --- 4. Add dispatch in transforms.py ---
    _add_dispatch(op, fn_name)

    # --- 5. Register in grammar.py ---
    _add_to_grammar(op, fn_name)

    # --- 6. Reload modules ---
    _reload_modules()

    print(f"[Injector] ✓ Op {op!r} injected and live in all modules.")
    return op


def _append_to_grid_ops(op: str, arity: int = 0):
    text = _PRIMITIVES_PATH.read_text(encoding="utf-8")
    insert = f'    "{op}": {arity},\n'
    # Insert before "FRACTAL_TILE"
    text = text.replace('    "FRACTAL_TILE": 1,', insert + '    "FRACTAL_TILE": 1,', 1)
    _PRIMITIVES_PATH.write_text(text, encoding="utf-8")


def _add_to_valid_ops(op: str):
    text = _TYPE_CHECKER_PATH.read_text(encoding="utf-8")
    # Find the closing } of VALID_OPS and prepend the new op
    text = re.sub(
        r'("SHIFT_PARALLELOGRAM","DIAGONAL_STACK_CHAIN",)',
        rf'\1"{op}",',
        text,
        count=1,
    )
    _TYPE_CHECKER_PATH.write_text(text, encoding="utf-8")


def _add_dispatch(op: str, fn_name: str):
    text = _TRANSFORMS_DISPATCH_PATH.read_text(encoding="utf-8")
    new_line = f'    if op=="{op}": return adv.{fn_name}(g,*args)\n'
    text = text.replace("    raise ValueError(op)", new_line + "    raise ValueError(op)", 1)
    _TRANSFORMS_DISPATCH_PATH.write_text(text, encoding="utf-8")


def _add_to_grammar(op: str, fn_name: str):
    text = _GRAMMAR_PATH.read_text(encoding="utf-8")
    # Add to SOLVER_FAMILIES set
    text = text.replace(
        '"diagonal_stack_chain",\n}',
        f'"diagonal_stack_chain","{fn_name}",\n}}',
        1,
    )
    # Add to primitive_programs
    new_block = textwrap.dedent(f"""
    if "{fn_name}" in families:
        out.append(Program((Instruction("{op}"),)))
""")
    text = text.replace("    return out\n", new_block + "    return out\n", 1)
    _GRAMMAR_PATH.write_text(text, encoding="utf-8")


def _reload_modules():
    """Reload DSL modules in-process so the new op is immediately available."""
    mods = [
        "arc_solver.dsl.advanced_transforms",
        "arc_solver.dsl.primitives",
        "arc_solver.dsl.type_checker",
        "arc_solver.dsl.transforms",
        "arc_solver.synthesis.grammar",
    ]
    for mod_name in mods:
        if mod_name in sys.modules:
            try:
                importlib.reload(sys.modules[mod_name])
            except Exception as e:
                print(f"[Injector] Warning: could not reload {mod_name}: {e}")
