from __future__ import annotations
import json
import time
from flask import Flask, request, jsonify
from threading import Lock

app = Flask(__name__)

# State lock
lock = Lock()

# Global Coordinator State
tasks_queue = []
assigned_tasks = {}  # task_id -> {worker_id, timestamp}
results = {}         # task_id -> {solved, source, program_str, worker_id}
primitives = []      # list of new code snippets generated by any worker

@app.route("/api/init_tasks", methods=["POST"])
def init_tasks():
    """Initialize or reset the central task pool (400 tasks)."""
    global tasks_queue, assigned_tasks, results
    data = request.json or {}
    task_ids = data.get("task_ids", [])
    with lock:
        tasks_queue = list(task_ids)
        assigned_tasks.clear()
        results.clear()
    return jsonify({"status": "ok", "count": len(task_ids)})

@app.route("/api/get_task", methods=["POST"])
def get_task():
    """Lease a task to a requesting Colab worker."""
    worker_id = request.json.get("worker_id", "unknown")
    with lock:
        # Clean up stale assignments (> 5 minutes timeout)
        now = time.time()
        for tid, info in list(assigned_tasks.items()):
            if now - info["timestamp"] > 300:
                print(f"[Coordinator] Re-queueing stale task {tid} from worker {info['worker_id']}")
                del assigned_tasks[tid]
                tasks_queue.append(tid)

        if not tasks_queue:
            return jsonify({"status": "empty", "task_id": None})

        task_id = tasks_queue.pop(0)
        assigned_tasks[task_id] = {"worker_id": worker_id, "timestamp": now}
        return jsonify({"status": "ok", "task_id": task_id})

@app.route("/api/submit_result", methods=["POST"])
def submit_result():
    """Receive task solution or miss, plus any newly generated DSL code."""
    data = request.json
    task_id = data.get("task_id")
    worker_id = data.get("worker_id")
    solved = data.get("solved", False)
    source = data.get("source", "none")
    program_str = data.get("program_str", "")
    new_primitive_code = data.get("new_primitive_code")

    with lock:
        if task_id in assigned_tasks:
            del assigned_tasks[task_id]
        
        results[task_id] = {
            "solved": solved,
            "source": source,
            "program_str": program_str,
            "worker_id": worker_id,
            "timestamp": time.time(),
        }

        if new_primitive_code and new_primitive_code not in primitives:
            primitives.append(new_primitive_code)
            print(f"[Coordinator] Received NEW PRIMITIVE from worker {worker_id} for task {task_id}")

    return jsonify({"status": "ok"})

@app.route("/api/primitives", methods=["GET"])
def get_primitives():
    """Provide list of all dynamic primitives discovered so far."""
    with lock:
        return jsonify({"status": "ok", "primitives": primitives})

@app.route("/api/status", methods=["GET"])
def status():
    """Return live metrics across all cloud workers."""
    with lock:
        total_solved = sum(1 for r in results.values() if r["solved"])
        return jsonify({
            "total_tasks": len(tasks_queue) + len(assigned_tasks) + len(results),
            "pending": len(tasks_queue),
            "in_progress": len(assigned_tasks),
            "completed": len(results),
            "solved": total_solved,
            "discovered_primitives_count": len(primitives),
            "results": results
        })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
