from __future__ import annotations
"""
auto_primitive_injector.py
--------------------------
Given a verified LLM-generated solve() function, injects it into the DSL
so the solver can use it immediately (both on disk and in the live module cache).
"""
import re
import importlib
import sys
import textwrap
from pathlib import Path
from typing import Callable, Optional

# Dynamically resolve dsl root directory from sys.modules or parent path
_THIS_FILE = Path(__file__).resolve()
_META_DIR = _THIS_FILE.parent
_ARC_SOLVER_ROOT = _META_DIR.parent

_DSL_ROOT = _ARC_SOLVER_ROOT / "dsl"
if not _DSL_ROOT.exists():
    for sys_p in sys.path:
        cand = Path(sys_p) / "arc_solver" / "dsl"
        if cand.exists():
            _DSL_ROOT = cand
            _ARC_SOLVER_ROOT = Path(sys_p) / "arc_solver"
            break

_TRANSFORMS_PATH = _DSL_ROOT / "advanced_transforms.py"
_PRIMITIVES_PATH = _DSL_ROOT / "primitives.py"
_TYPE_CHECKER_PATH = _DSL_ROOT / "type_checker.py"
_TRANSFORMS_DISPATCH_PATH = _DSL_ROOT / "transforms.py"
_GRAMMAR_PATH = _ARC_SOLVER_ROOT / "synthesis" / "grammar.py"


def _op_name(task_id: str) -> str:
    """Derive a deterministic op name from the task ID."""
    safe = task_id.replace("-", "_").upper()
    return f"LLM_{safe}"


def inject_llm_solve(task_id: str, solve_fn: Callable) -> str:
    """
    Inject a verified LLM solve() function into the DSL.
    """
    op = _op_name(task_id)
    fn_name = op.lower()
    code: str = getattr(solve_fn, "_llm_code", None) or ""

    if not code:
        print(f"[Injector] No code attached to solve_fn for {task_id}.")
        return op

    if not _TRANSFORMS_PATH.exists():
        print(f"[Injector] File {_TRANSFORMS_PATH} not found. Skipping disk injection.")
        return op

    # --- 1. Append to advanced_transforms.py ---
    full_fn = textwrap.dedent(f"""

    # LLM-generated primitive for task {task_id}
    def {fn_name}(grid, background=0):
        \"\"\"Auto-generated by Gemini Flash for task {task_id}.\"\"\"
        import numpy as np
        g = as_grid(grid).copy()

    """)
    indented_code = textwrap.indent(code, "    ") + "\n    return solve(g)\n"
    full_fn += indented_code

    try:
        with open(_TRANSFORMS_PATH, "a", encoding="utf-8") as f:
            f.write(full_fn)
        print(f"[Injector] Appended {fn_name}() to {_TRANSFORMS_PATH.name}")

        # --- 2. Register in primitives.py ---
        if _PRIMITIVES_PATH.exists():
            _append_to_grid_ops(op, arity=0)

        # --- 3. Add to VALID_OPS in type_checker.py ---
        if _TYPE_CHECKER_PATH.exists():
            _add_to_valid_ops(op)

        # --- 4. Add dispatch in transforms.py ---
        if _TRANSFORMS_DISPATCH_PATH.exists():
            _add_dispatch(op, fn_name)

        # --- 5. Register in grammar.py ---
        if _GRAMMAR_PATH.exists():
            _add_to_grammar(op, fn_name)

        # --- 6. Reload modules ---
        _reload_modules()

        print(f"[Injector] OK Op {op!r} injected and live in all modules.")
    except Exception as e:
        print(f"[Injector] Disk injection warning: {e}")

    return op


def _append_to_grid_ops(op: str, arity: int = 0):
    text = _PRIMITIVES_PATH.read_text(encoding="utf-8")
    if f'"{op}"' in text:
        return
    insert = f'    "{op}": {arity},\n'
    text = text.replace('    "FRACTAL_TILE": 1,', insert + '    "FRACTAL_TILE": 1,', 1)
    _PRIMITIVES_PATH.write_text(text, encoding="utf-8")


def _add_to_valid_ops(op: str):
    text = _TYPE_CHECKER_PATH.read_text(encoding="utf-8")
    if f'"{op}"' in text:
        return
    text = re.sub(
        r'("SHIFT_PARALLELOGRAM","DIAGONAL_STACK_CHAIN",)',
        rf'\1"{op}",',
        text,
        count=1,
    )
    _TYPE_CHECKER_PATH.write_text(text, encoding="utf-8")


def _add_dispatch(op: str, fn_name: str):
    text = _TRANSFORMS_DISPATCH_PATH.read_text(encoding="utf-8")
    if f'"{op}"' in text:
        return
    new_line = f'    if op=="{op}": return adv.{fn_name}(g,*args)\n'
    text = text.replace("    raise ValueError(op)", new_line + "    raise ValueError(op)", 1)
    _TRANSFORMS_DISPATCH_PATH.write_text(text, encoding="utf-8")


def _add_to_grammar(op: str, fn_name: str):
    text = _GRAMMAR_PATH.read_text(encoding="utf-8")
    if f'"{fn_name}"' in text:
        return
    text = text.replace(
        '"diagonal_stack_chain",\n}',
        f'"diagonal_stack_chain","{fn_name}",\n}}',
        1,
    )
    new_block = textwrap.dedent(f"""
    if "{fn_name}" in families:
        out.append(Program((Instruction("{op}"),)))
""")
    # Replace last return out with new block + return out
    idx = text.rfind("    return out")
    if idx != -1:
        text = text[:idx] + new_block + "\n    return out\n"
    _GRAMMAR_PATH.write_text(text, encoding="utf-8")


def _reload_modules():
    mods = [
        "arc_solver.dsl.advanced_transforms",
        "arc_solver.dsl.primitives",
        "arc_solver.dsl.type_checker",
        "arc_solver.dsl.transforms",
        "arc_solver.synthesis.grammar",
    ]
    for mod_name in mods:
        if mod_name in sys.modules:
            try:
                importlib.reload(sys.modules[mod_name])
            except Exception as e:
                print(f"[Injector] Warning: could not reload {mod_name}: {e}")
