from __future__ import annotations
import os
import json
import time
from pathlib import Path
from flask import Flask, request, jsonify, render_template_string
from threading import Lock

app = Flask(__name__)
lock = Lock()

# Global Coordinator State
tasks_queue = []
assigned_tasks = {}  # task_id -> {worker_id, timestamp}
results = {}         # task_id -> {solved, source, program_str, worker_id, timestamp}
workers = {}         # worker_id -> {last_seen, tasks_completed, tasks_solved, current_task}
primitives = []      # list of new code snippets generated by any worker

def load_initial_tasks():
    global tasks_queue
    data_file = Path("data/arc-prize-2026-arc-agi-2/arc-agi_training_challenges.json")
    if not data_file.exists():
        data_file = Path("arc-neurosymbolic-v1/data/arc-prize-2026-arc-agi-2/arc-agi_training_challenges.json")
    
    if data_file.exists():
        try:
            with open(data_file, "r", encoding="utf-8") as f:
                ch = json.load(f)
                tasks_queue = list(ch.keys())
                print(f"[Coordinator] Automatically loaded {len(tasks_queue)} tasks into queue!")
        except Exception as e:
            print(f"[Coordinator] Error loading initial tasks: {e}")

load_initial_tasks()

# Premium Glassmorphism Live Web Dashboard
HTML_DASHBOARD = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ARC-AGI-2 Distributed Cluster Dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Inter', sans-serif; }
        body { background: #0f172a; color: #f8fafc; padding: 2rem; }
        h1 { color: #38bdf8; font-size: 1.8rem; margin-bottom: 0.5rem; display: flex; align-items: center; gap: 10px; }
        .subtitle { color: #94a3b8; font-size: 0.95rem; margin-bottom: 2rem; }
        .grid-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.2rem; margin-bottom: 2rem; }
        .card { background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 12px; padding: 1.2rem; }
        .card-title { color: #64748b; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; margin-bottom: 0.5rem; }
        .card-value { font-size: 2rem; font-weight: 700; color: #f1f5f9; }
        .card-value.green { color: #4ade80; }
        .card-value.blue { color: #38bdf8; }
        .card-value.amber { color: #fbbf24; }
        
        .section-title { font-size: 1.2rem; margin-bottom: 1rem; color: #e2e8f0; display: flex; justify-content: space-between; align-items: center; }
        table { width: 100%; border-collapse: collapse; background: rgba(30, 41, 59, 0.5); border-radius: 8px; overflow: hidden; margin-bottom: 2rem; }
        th, td { padding: 0.9rem 1.2rem; text-align: left; border-bottom: 1px solid rgba(255, 255, 255, 0.05); font-size: 0.9rem; }
        th { background: rgba(15, 23, 42, 0.6); color: #94a3b8; font-weight: 600; text-transform: uppercase; font-size: 0.75rem; }
        tr:hover { background: rgba(255, 255, 255, 0.03); }
        .badge { display: inline-block; padding: 0.25rem 0.6rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
        .badge-active { background: rgba(74, 222, 128, 0.2); color: #4ade80; border: 1px solid rgba(74, 222, 128, 0.4); }
        .badge-working { background: rgba(56, 189, 248, 0.2); color: #38bdf8; border: 1px solid rgba(56, 189, 248, 0.4); }
        .badge-idle { background: rgba(148, 163, 184, 0.2); color: #94a3b8; }
        .pulse { display: inline-block; width: 8px; height: 8px; border-radius: 50%; background: #4ade80; box-shadow: 0 0 8px #4ade80; margin-right: 6px; }
    </style>
</head>
<body>
    <h1><span class="pulse"></span> ARC-AGI-2 Multi-Cloud Distributed Cluster</h1>
    <div class="subtitle">Real-time status of Colab workers, active task assignments & discovered primitives</div>

    <div class="grid-stats">
        <div class="card"><div class="card-title">Connected Workers</div><div class="card-value blue" id="active-workers">0</div></div>
        <div class="card"><div class="card-title">Tasks In Progress</div><div class="card-value amber" id="in-progress">0</div></div>
        <div class="card"><div class="card-title">Tasks Solved</div><div class="card-value green" id="solved-count">0</div></div>
        <div class="card"><div class="card-title">Tasks Completed</div><div class="card-value" id="completed-count">0 / 0</div></div>
        <div class="card"><div class="card-title">Discovered Primitives</div><div class="card-value blue" id="primitives-count">0</div></div>
    </div>

    <div class="section-title">Active Cloud Workers (<span id="worker-count-header">0</span>)</div>
    <table>
        <thead>
            <tr>
                <th>Worker ID</th>
                <th>Status</th>
                <th>Current Task</th>
                <th>Completed</th>
                <th>Solved</th>
                <th>Last Seen</th>
            </tr>
        </thead>
        <tbody id="workers-body">
            <tr><td colspan="6" style="text-align: center; color: #64748b;">No workers connected yet...</td></tr>
        </tbody>
    </table>

    <script>
        async function fetchStatus() {
            try {
                const res = await fetch('/api/status');
                const data = await res.json();
                document.getElementById('active-workers').innerText = data.active_workers_count;
                document.getElementById('worker-count-header').innerText = data.active_workers_count;
                document.getElementById('in-progress').innerText = data.in_progress;
                document.getElementById('solved-count').innerText = data.solved;
                document.getElementById('completed-count').innerText = `${data.completed} / ${data.total_tasks}`;
                document.getElementById('primitives-count').innerText = data.discovered_primitives_count;

                const tbody = document.getElementById('workers-body');
                const entries = Object.entries(data.workers);
                if (entries.length === 0) {
                    tbody.innerHTML = '<tr><td colspan="6" style="text-align: center; color: #64748b;">No workers connected yet...</td></tr>';
                    return;
                }
                tbody.innerHTML = entries.map(([id, info]) => {
                    const statusBadge = info.is_active ? 
                        (info.current_task ? '<span class="badge badge-working">Working</span>' : '<span class="badge badge-active">Active</span>') : 
                        '<span class="badge badge-idle">Offline</span>';
                    return `
                        <tr>
                            <td style="font-weight: 600; color: #38bdf8;">${id}</td>
                            <td>${statusBadge}</td>
                            <td style="font-family: monospace; color: #fbbf24;">${info.current_task || '-'}</td>
                            <td>${info.tasks_completed}</td>
                            <td style="color: #4ade80;">${info.tasks_solved}</td>
                            <td>${info.last_seen_sec}s ago</td>
                        </tr>
                    `;
                }).join('');
            } catch (e) {
                console.error("Error fetching status:", e);
            }
        }
        setInterval(fetchStatus, 2000);
        fetchStatus();
    </script>
</body>
</html>
"""

@app.route("/")
def index():
    """Render live HTML web dashboard."""
    return render_template_string(HTML_DASHBOARD)

@app.route("/api/init_tasks", methods=["POST"])
def init_tasks():
    global tasks_queue, assigned_tasks, results
    data = request.json or {}
    task_ids = data.get("task_ids", [])
    with lock:
        tasks_queue = list(task_ids)
        assigned_tasks.clear()
        results.clear()
        workers.clear()
    return jsonify({"status": "ok", "count": len(task_ids)})

@app.route("/api/get_task", methods=["POST"])
def get_task():
    worker_id = request.json.get("worker_id", "unknown")
    now = time.time()
    with lock:
        # Update worker record
        if worker_id not in workers:
            workers[worker_id] = {"last_seen": now, "tasks_completed": 0, "tasks_solved": 0, "current_task": None}
        else:
            workers[worker_id]["last_seen"] = now

        # Clean up stale assignments (> 5 minutes timeout)
        for tid, info in list(assigned_tasks.items()):
            if now - info["timestamp"] > 300:
                print(f"[Coordinator] Re-queueing stale task {tid} from worker {info['worker_id']}")
                del assigned_tasks[tid]
                tasks_queue.append(tid)

        if not tasks_queue:
            workers[worker_id]["current_task"] = None
            return jsonify({"status": "empty", "task_id": None})

        task_id = tasks_queue.pop(0)
        assigned_tasks[task_id] = {"worker_id": worker_id, "timestamp": now}
        workers[worker_id]["current_task"] = task_id
        
        print(f"[Coordinator] Assigned task {task_id} -> Worker: {worker_id}")
        return jsonify({"status": "ok", "task_id": task_id})

@app.route("/api/submit_result", methods=["POST"])
def submit_result():
    data = request.json
    task_id = data.get("task_id")
    worker_id = data.get("worker_id")
    solved = data.get("solved", False)
    source = data.get("source", "none")
    program_str = data.get("program_str", "")
    new_primitive_code = data.get("new_primitive_code")
    now = time.time()

    with lock:
        if task_id in assigned_tasks:
            del assigned_tasks[task_id]
        
        results[task_id] = {
            "solved": solved,
            "source": source,
            "program_str": program_str,
            "worker_id": worker_id,
            "timestamp": now,
        }

        # Automatically re-queue unsolved tasks so workers keep trying them
        if not solved:
            if task_id not in tasks_queue:
                tasks_queue.append(task_id)

        if worker_id in workers:
            workers[worker_id]["last_seen"] = now
            workers[worker_id]["tasks_completed"] += 1
            if solved:
                workers[worker_id]["tasks_solved"] += 1
            workers[worker_id]["current_task"] = None

        if new_primitive_code and new_primitive_code not in primitives:
            primitives.append(new_primitive_code)
            print(f"[Coordinator] Received NEW PRIMITIVE from worker {worker_id} for task {task_id}")

    return jsonify({"status": "ok"})

@app.route("/api/primitives", methods=["GET"])
def get_primitives():
    with lock:
        return jsonify({"status": "ok", "primitives": primitives})

@app.route("/api/status", methods=["GET"])
def status():
    now = time.time()
    with lock:
        total_solved = sum(1 for r in results.values() if r["solved"])
        active_workers = {
            wid: {
                "last_seen_sec": int(now - info["last_seen"]),
                "is_active": (now - info["last_seen"]) < 60,
                "tasks_completed": info["tasks_completed"],
                "tasks_solved": info["tasks_solved"],
                "current_task": info["current_task"]
            }
            for wid, info in workers.items()
        }

        assigned_details = [
            {
                "task_id": tid,
                "worker_id": info["worker_id"],
                "elapsed_sec": int(now - info["timestamp"]),
                "leased_time": time.strftime("%H:%M:%S", time.localtime(info["timestamp"]))
            }
            for tid, info in assigned_tasks.items()
        ]

        active_count = sum(1 for w in active_workers.values() if w["is_active"])

        return jsonify({
            "total_tasks": len(tasks_queue) + len(assigned_tasks) + len(results),
            "pending": len(tasks_queue),
            "in_progress": len(assigned_tasks),
            "completed": len(results),
            "solved": total_solved,
            "discovered_primitives_count": len(primitives),
            "active_workers_count": active_count,
            "workers": active_workers,
            "assigned_details": assigned_details,
            "results": results
        })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
